CREATE DATABASE SAC_FIDELITY;

USE SAC_FIDELITY

CREATE TABLE USER(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(25),
  email VARCHAR(50),
  password VARCHAR(255)
);

CREATE TABLE CUSTOMER(
  id INT PRIMARY KEY AUTO_INCREMENT,
  firstname VARCHAR(25),
  address VARCHAR(255),
  zip_code CHAR(5),
  city VARCHAR(50),
  phone_number CHAR(10),
  pay INT,
  id_user INT
);

CREATE TABLE ROLE(
  label CHAR(3),
  description VARCHAR(20)
);

CREATE TABLE ADMINISTRATOR(
  id INT PRIMARY KEY AUTO_INCREMENT,
  firstname VARCHAR(25),
  id_user INT,
  label_role INT
);

CREATE TABLE PARTNER(
  id INT PRIMARY KEY AUTO_INCREMENT,
  siret CHAR(14),
  start_partnership DATE,
  status BOOLEAN,
  logo VARCHAR(255),
  link VARCHAR(255),
  id_user INT
);

CREATE TABLE CONTRIBUTION(
  id INT PRIMARY KEY AUTO_INCREMENT,
  payment_date DATE,
  price DOUBLE,
  id_partner INT
);

CREATE TABLE BASKET(
  id INT PRIMARY KEY AUTO_INCREMENT,
  date_validation DATE,
  status BOOLEAN,
  id_customer INT
);

CREATE TABLE HISTORICAL(
  prix INT,
  change_date DATE,
  id_product INT
);

CREATE TABLE PRODUCT(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(25),
  description VARCHAR(255),
  image VARCHAR(255)
);

CREATE TABLE INCLUDE(
  count INT,
  id_product INT,
  id_basket INT
);

CREATE TABLE PRESTATION (
  id INT PRIMARY KEY AUTO_INCREMENT,
  reduction INT,
  poINTs INT,
  id_product INT,
  id_partner INT
);

CREATE TABLE OBJECT (
  id INT PRIMARY KEY AUTO_INCREMENT,
  actual_price DOUBLE,
  id_product INT
);


CREATE TABLE RATING (
  id INT PRIMARY KEY AUTO_INCREMENT,
  ratingNumber INT,
  title VARCHAR(255),
  comments VARCHAR(255),
  created datetime,
  id_product INT,
  id_user INT
);

ALTER TABLE CONTRIBUTION ADD FOREIGN KEY (id_partner) REFERENCES PARTNER(id);
ALTER TABLE CUSTOMER ADD FOREIGN KEY (id_user) REFERENCES USER(id);
ALTER TABLE PARTNER ADD FOREIGN KEY (id_user) REFERENCES USER(id);
ALTER TABLE ADMINISTRATOR ADD FOREIGN KEY (id_user) REFERENCES USER(id);
ALTER TABLE ADMINISTRATOR ADD FOREIGN KEY (label_role) REFERENCES ROLE(label);
ALTER TABLE INCLUDE ADD FOREIGN KEY (id_product) REFERENCES PRODUCT(id);
ALTER TABLE INCLUDE ADD FOREIGN KEY (id_basket) REFERENCES BASKET(id);
ALTER TABLE HISTORICAL ADD FOREIGN KEY (id_product) REFERENCES PRODUCT(id);
ALTER TABLE BASKET ADD FOREIGN KEY (id_customer) REFERENCES CUSTOMER(id);
ALTER TABLE PRESTATION ADD FOREIGN KEY (id_product) REFERENCES PRODUCT(id);
ALTER TABLE PRESTATION ADD FOREIGN KEY (id_partner) REFERENCES PARTNER(id);
ALTER TABLE OBJECT ADD FOREIGN KEY (id_product) REFERENCES PRODUCT(id);
ALTER TABLE RATING ADD FOREIGN KEY (id_product) REFERENCES PRODUCT(id);
ALTER TABLE RATING ADD FOREIGN KEY (id_user) REFERENCES USER(id);

